#!/usr/bin/env node

const {
  SUPABASE_ENV,
  createSupabaseClients,
  fail,
  loadLocalEnv,
  missingEnv,
  ok,
  printHeader,
  skipMissing,
  skipped,
  warn,
} = require("./validation-utils.cjs");

async function anonSelect(client, table, columns = "id") {
  return client.from(table).select(columns).limit(1);
}

function isPermissionError(error) {
  const message = `${error?.message ?? ""} ${error?.details ?? ""}`.toLowerCase();
  return message.includes("permission") || message.includes("row-level security") || message.includes("jwt");
}

async function expectPrivateTable(anon, table, label) {
  const { data, error } = await anonSelect(anon, table);
  if (error) {
    if (isPermissionError(error)) ok(`${label} is not broadly readable through anon access`);
    else warn(`${label} anon check returned non-RLS error: ${error.message}`);
    return;
  }

  if (Array.isArray(data) && data.length > 0) {
    fail(`${label} returned rows through anon access; private observation data may be broadly readable`);
  } else {
    warn(`${label} returned no anon rows. This is safe for this dataset, but user-scoping needs live auth test users to prove isolation.`);
  }
}

async function run() {
  loadLocalEnv();
  printHeader("RLS Validation");

  const missing = missingEnv(SUPABASE_ENV);
  if (skipMissing(missing, "RLS validation")) return;

  const { anon, service } = createSupabaseClients();

  const { error: serviceError } = await service.from("observations").select("id", { count: "exact", head: true }).limit(1);
  if (serviceError) {
    fail(`Service-role schema check failed before RLS validation: ${serviceError.message}`);
    return;
  }
  ok("Service-role schema access works for validation");

  await expectPrivateTable(anon, "observations", "observations");
  await expectPrivateTable(anon, "observation_media", "observation media");
  await expectPrivateTable(anon, "analysis_runs", "analysis runs");

  const { data: species, error: speciesError } = await anon.from("species_reference").select("id, scientific_name").limit(1);
  if (speciesError) fail(`Public species reference is not readable through anon access: ${speciesError.message}`);
  else ok(`Public species reference is readable${species?.length ? "" : " (no rows returned)"}`);

  skipped("Full cross-user RLS isolation requires two real authenticated test users; no auth credentials are stored or generated by this script.");
}

run().catch((error) => {
  fail(error instanceof Error ? error.message : String(error));
});
