// ─── /api/send — Email Delivery (Resend) ────────────────────────────────────
import { NextRequest, NextResponse } from 'next/server'
import { getRunById } from '@/lib/supabase/admin'
import { log, generateRequestId } from '@/lib/research/logger'

export async function POST(request: NextRequest) {
  const requestId = generateRequestId()
  const apiKey = process.env.RESEND_API_KEY

  if (!apiKey) {
    return NextResponse.json({
      ok: false,
      message: 'Email delivery is not configured. Set RESEND_API_KEY in environment variables.',
      retryable: false,
    }, { status: 503 })
  }

  let body: { runId: string; email: string }
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ ok: false, message: 'Invalid JSON' }, { status: 400 })
  }

  if (!body.runId || !body.email) {
    return NextResponse.json({ ok: false, message: 'runId and email are required' }, { status: 400 })
  }

  // Get run data
  const data = await getRunById(body.runId)
  if (!data?.result) {
    return NextResponse.json({ ok: false, message: 'Run not found' }, { status: 404 })
  }

  try {
    const { Resend } = await import('resend')
    const resend = new Resend(apiKey)

    const title = data.result.title ?? data.run.query
    const summary = data.result.executive_summary ?? 'See attached report.'

    const { error } = await resend.emails.send({
      from: 'Verdant Research <onboarding@resend.dev>',
      to: [body.email],
      subject: `Research Report: ${title}`,
      html: `
        <div style="font-family: Georgia, serif; max-width: 600px; margin: 0 auto; padding: 24px;">
          <h1 style="color: #1A2F23; font-size: 24px; font-weight: 400; margin-bottom: 16px;">${title}</h1>
          <p style="color: #434841; font-size: 14px; line-height: 1.7;">${summary}</p>
          <hr style="border: none; border-top: 1px solid #e0e0e0; margin: 24px 0;">
          <p style="color: #737870; font-size: 12px;">
            Generated by <strong>Verdant AI Research Platform</strong><br>
            View the full report at <a href="https://verdantai.vercel.app/research?q=${encodeURIComponent(data.run.query)}" style="color: #2E5D3E;">verdantai.vercel.app</a>
          </p>
        </div>
      `,
    })

    if (error) {
      log.error(`Resend failed: ${error.message}`, { requestId })
      return NextResponse.json({ ok: false, message: error.message, retryable: true }, { status: 500 })
    }

    log.info('Email sent successfully', { requestId, runId: body.runId })
    return NextResponse.json({ ok: true, message: 'Email sent' })

  } catch (err) {
    const message = err instanceof Error ? err.message : 'Email delivery failed'
    log.error(`Email send error: ${message}`, { requestId })
    return NextResponse.json({ ok: false, message, retryable: true }, { status: 500 })
  }
}
